import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Steph O. - Front-End Developer + Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/stephorc-logo.svg" />
      </Head>

      <header>
        <h1>Test</h1>
      </header>
    </div>
  )
}
